name: test
on:
- pull_request
jobs:
  sqlite-nio_bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  sqlite-nio_xenial:
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  # sqlite-nio_catalina:
  #   runs-on: macOS-10.15
  #   steps:
  #   - uses: actions/checkout@v1
  #   - run: swift test --sanitize=thread
  # sqlite-nio_ios13:
  #   runs-on: macOS-10.15
  #   steps:
  #   - uses: actions/checkout@v1
  #   - run: xcodebuild test -destination 'name=iPhone 11' -scheme 'sqlite-nio'
  sqlite-kit:
    container: 
      image: vapor/swift:5.2
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - run: git clone -b master https://github.com/vapor/sqlite-kit.git
      working-directory: ./
    - run: swift package edit sqlite-nio --revision ${{ github.sha }}
      working-directory: ./sqlite-kit
    - run: swift test --enable-test-discovery --sanitize=thread
      working-directory: ./sqlite-kit
  fluent-sqlite-driver:
    container: 
      image: vapor/swift:5.2
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - run: git clone -b master https://github.com/vapor/fluent-sqlite-driver.git
      working-directory: ./
    - run: swift package edit sqlite-nio --revision ${{ github.sha }}
      working-directory: ./fluent-sqlite-driver
    - run: swift test --enable-test-discovery --sanitize=thread
      working-directory: ./fluent-sqlite-driver
