name: test
on:
- pull_request
jobs:
  bionic:
    container: 
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  xenial:
    container: 
      image: vapor/swift:5.1-xenial
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  ios:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  ios:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - run: xcodebuild test -destination 'name=iPhone 11' -scheme 'sqlite-nio'
